### ISSUE TITLE
Error with test

### ISSUE THREAD

**Issue by MailSuesarn** [LiYuhangUSTC/Sketch2Face#4]
CustomDatasetDataLoader
dataset [AlignedDataset] was created
dual
Load model from:  ./checkpoints/pretrained/latest_net_G.pth
Load model from:  ./checkpoints/pretrained/latest_net_G_sap.pth
Traceback (most recent call last):
  File "test.py", line 56, in <module>
    for i, data in enumerate(dataset):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/gdrive/MyDrive/Colab Notebooks/Sketch2Face/data/aligned_dataset.py", line 52, in __getitem__
    rand_index = np.random.randint(len(self.C_list_paths[index]))
  File "mtrand.pyx", line 746, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1254, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high

**Comment by LiYuhangUSTC** [comment]
Seems you are using an empty dataset, e.g. pointing the test dataset to an empty directory or something like that.
